# Generated by Django 4.0 on 2021-12-09 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_address_address_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='apartment_address',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street_address',
            new_name='address2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_address',
            new_name='address',
        ),
    ]
