# Generated by Django 4.0 on 2021-12-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_apartment_address_address_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
