# Generated by Django 4.0 on 2021-12-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_orderitem_wishlist_wishlistitem_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='items',
            field=models.ManyToManyField(to='core.WishlistItem'),
        ),
    ]
